"""Agrega categorias y perfiles modulares

Revision ID: 1c84dd86a50c
Revises: e34533c27a97
Create Date: 2026-10-05 21:14:34.485737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c84dd86a50c'
down_revision: Union[str, Sequence[str], None] = 'e34533c27a97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
