"""add plantillas suscripciones y auditoria

Revision ID: 664f7b4bf5d0
Revises: 0cf421c392b1
Create Date: 2026-08-01 13:16:56.506783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '664f7b4bf5d0'
down_revision: Union[str, Sequence[str], None] = '0cf421c392b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantillas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ruta_archivo', sa.String(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plantillas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plantillas_id'), ['id'], unique=False)

    op.create_table('auditoria_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(), nullable=False),
    sa.Column('ip_origen', sa.String(), nullable=True),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditoria_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_logs_id'), ['id'], unique=False)

    op.create_table('demandas_generadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('plantilla_id', sa.Integer(), nullable=True),
    sa.Column('dni_actor', sa.Integer(), nullable=True),
    sa.Column('nombre_actor', sa.String(), nullable=True),
    sa.Column('estado_operativo', sa.String(), nullable=True),
    sa.Column('ip_origen', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plantilla_id'], ['plantillas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('demandas_generadas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demandas_generadas_id'), ['id'], unique=False)

    op.create_table('suscripciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('demandas_restantes', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    with op.batch_alter_table('suscripciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suscripciones_id'), ['id'], unique=False)

    with op.batch_alter_table('demanda_generada', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demanda_generada_dni_actor'))
        batch_op.drop_index(batch_op.f('ix_demanda_generada_id'))

    op.drop_table('demanda_generada')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('activo')

    op.create_table('demanda_generada',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dni_actor', sa.INTEGER(), nullable=True),
    sa.Column('nombre_actor', sa.VARCHAR(), nullable=False),
    sa.Column('fecha_creacion', sa.DATETIME(), nullable=True),
    sa.Column('estado_operativo', sa.VARCHAR(), nullable=True),
    sa.Column('ip_origen', sa.VARCHAR(), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('demanda_generada', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demanda_generada_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_demanda_generada_dni_actor'), ['dni_actor'], unique=False)

    with op.batch_alter_table('suscripciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suscripciones_id'))

    op.drop_table('suscripciones')
    with op.batch_alter_table('demandas_generadas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demandas_generadas_id'))

    op.drop_table('demandas_generadas')
    with op.batch_alter_table('auditoria_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_logs_id'))

    op.drop_table('auditoria_logs')
    with op.batch_alter_table('plantillas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plantillas_id'))

    op.drop_table('plantillas')
    # ### end Alembic commands ###
